Repository openshift/whereabouts-cni, pull requests merged in 2023-04, with the labels that each got.

#121 OCPBUGS-11324: respect requested allocation range when exluding ranges [backport 4.14]
  pkg/allocate/allocate.go
  pkg/allocate/allocate_test.go
Labels: bugzilla/valid-bug, lgtm, approved, jira/severity-critical, jira/valid-bug, jira/valid-reference

#125 OCPBUGS-7301: Invalid ipv6 backport 4.13
  .github/workflows/build.yml
  .github/workflows/test.yml
  Dockerfile
  Dockerfile.arm64
  cmd/whereabouts_test.go
  e2e/client/ippool.go
  go.mod
  go.sum
  pkg/api/whereabouts.cni.cncf.io/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/fake/fake_ippool.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/fake/fake_overlappingrangeipreservation.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/fake/fake_whereabouts.cni.cncf.io_client.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/ippool.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation.go
  pkg/client/clientset/versioned/typed/whereabouts.cni.cncf.io/v1alpha1/whereabouts.cni.cncf.io_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/whereabouts.cni.cncf.io/interface.go
  pkg/client/informers/externalversions/whereabouts.cni.cncf.io/v1alpha1/interface.go
  pkg/client/informers/externalversions/whereabouts.cni.cncf.io/v1alpha1/ippool.go
  pkg/client/informers/externalversions/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation.go
  pkg/client/listers/whereabouts.cni.cncf.io/v1alpha1/expansion_generated.go
  pkg/client/listers/whereabouts.cni.cncf.io/v1alpha1/ippool.go
  pkg/client/listers/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controlloop/pod_controller_test.go
  pkg/storage/kubernetes/ipam.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#122 OCPBUGS-11322: respect requested allocation range when exluding ranges [Backport 4.13]
  pkg/allocate/allocate.go
  pkg/allocate/allocate_test.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#123 OCPBUGS-11321: respect requested allocation range when exluding ranges [Backport 4.12]
  pkg/allocate/allocate.go
  pkg/allocate/allocate_test.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference

#127 [release-4.13] OCPBUGS-11427: Fix network status annotation to k8s.v1.cni.cncf.io/network-status
  pkg/reconciler/ip_test.go
  pkg/reconciler/wrappedPod.go
  pkg/reconciler/wrappedPod_test.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#109 OCPBUGS-7429: Invalid ipv6 backport 4.12
  pkg/storage/kubernetes/ipam.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#124 OCPBUGS-11067: respect requested allocation range when exluding ranges [backport 4.11]
  pkg/allocate/allocate.go
  pkg/allocate/allocate_test.go
Labels: bugzilla/valid-bug, cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
