Repository openshift/whereabouts-cni, pull requests merged in 2023-07, with the labels that each got.

#140 Restores RHEL specific binary copy and updates to rhel9/8
  Dockerfile.openshift
Labels: lgtm, approved

#144 Bug 16002: Change default binary to RHEL8 image
  Dockerfile.openshift
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/valid-bug

#137 Downstream sync july23
  .github/dependabot.yml
  .github/workflows/image-build.yml
  .github/workflows/image-push-master.yml
  .github/workflows/image-push-release.yml
  Dockerfile.openshift
  README.md
  cmd/whereabouts.go
  cmd/whereabouts_test.go
  doc/crds/daemonset-install.yaml
  doc/extended-configuration.md
  e2e/e2e_test.go
  hack/e2e-setup-kind-cluster.sh
  pkg/allocate/allocate.go
  pkg/allocate/allocate_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controlloop/pod.go
  pkg/iphelpers/iphelpers.go
  pkg/iphelpers/iphelpers_test.go
  pkg/storage/kubernetes/ipam.go
  pkg/storage/storage.go
  script/install-cni.sh
Labels: lgtm, approved

#147 Bug 16136: Introduce entrypoint.sh to call ip-control-loop based on RHEL ver
  Dockerfile.openshift
  entrypoint.sh
Labels: lgtm, approved

#167 OCPBUGS-15905: Denormalize IP name before checking if pod is alive [Backport 4.14]
  pkg/reconciler/iploop.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference
