Repository openshift/whereabouts-cni, pull requests merged in 2024-06, with the labels that each got.

#286 OCPBUGS-34929: [release-4.16] Use IP to identify orphaned allocation to be deleted
  cmd/whereabouts.go
  pkg/allocate/allocate.go
  pkg/reconciler/ip_test.go
  pkg/reconciler/iploop.go
  pkg/storage/kubernetes/ipam.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#288 OCPBUGS-35081: [release-4.15] Use IP to identify orphaned allocation to be deleted
  cmd/whereabouts.go
  pkg/allocate/allocate.go
  pkg/reconciler/ip_test.go
  pkg/reconciler/iploop.go
  pkg/storage/kubernetes/ipam.go
Labels: cherry-pick-approved, lgtm, approved, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference

#285 NP-1045:Update owners
  OWNERS
Labels: lgtm, approved, jira/valid-reference

#293 OCPBUGS-35923: [release-4.16] Return previous IP allocation for add cmd
  .gitignore
  cmd/whereabouts.go
  cmd/whereabouts_test.go
  doc/crds/whereabouts.cni.cncf.io_ippools.yaml
  doc/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
  e2e/client/replicaset.go
  e2e/e2e_test.go
  e2e/poolconsistency/checker.go
  e2e/poolconsistency/poolconsistency_test.go
  e2e/retrievers/pod.go
  pkg/allocate/allocate.go
  pkg/allocate/allocate_test.go
  pkg/api/whereabouts.cni.cncf.io/v1alpha1/ippool_types.go
  pkg/api/whereabouts.cni.cncf.io/v1alpha1/overlappingrangeipreservation_types.go
  pkg/api/whereabouts.cni.cncf.io/v1alpha1/zz_generated.deepcopy.go
  pkg/storage/kubernetes/ipam.go
  pkg/storage/storage.go
  pkg/types/types.go
Labels: cherry-pick-approved, lgtm, approved, staff-eng-approved, backport-risk-assessed, jira/severity-critical, jira/valid-bug, jira/valid-reference
